server:
  port: 8080
  context-path: /
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5 #thymeleaf单标记问题
    cache: false #关闭thymeleaf缓存
    encoding: utf-8
  jackson:
    default-property-inclusion: non_null #输入json的时候，如果有属性值为null而不打印该属性
mybatis:
  type-aliases-package: com.brander.common.domain #指定domain类的基包
  mapper-locations: classpath:mapper/*.xml #指定*Mapper.xml的位置
  config-location: classpath:mybatis-config.xml
  check-config-location: true

#自定义配置
myconfig:
  version: 1.0.0
  weburl: form1.cn
  webname: SpringbootTest
  adminname: 后台管理系统